Tarnawski\GrimeDetectorBundle\Entity\Word:
    type: entity
    table: word
    repositoryClass: Tarnawski\GrimeDetectorBundle\Repository\WordRepository
    id:
        name:
            column: name
            type: string
            unique: true
            nullable: false
            length: 255
    fields:
        positive:
            column: positive
            type: integer
            options:
                default: 0
        negative:
            column: negative
            type: integer
            options:
                default: 0

    lifecycleCallbacks: {  }