services:
  tarnawski.grime_detector.word.repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - Tarnawski\GrimeDetectorBundle\Entity\Word

  tarnawski.grime_detector.service.statistic_service:
    class: Tarnawski\GrimeDetectorBundle\Service\StatisticService
    arguments:
      - '@doctrine.orm.entity_manager'

  tarnawski.grime_detector.word_tokenizer:
    class: Tarnawski\GrimeDetectorBundle\Tokenizer\WordTokenizer

  tarnawski.grime_detector.lowercase_normalizer:
    class: Tarnawski\GrimeDetectorBundle\Normalizer\LowercaseNormalizer

  tarnawski.grime_detector.stop_words_normalizer:
    class: Tarnawski\GrimeDetectorBundle\Normalizer\StopWordsNormalizer

  tarnawski.grime_detector.unique_normalizer:
    class: Tarnawski\GrimeDetectorBundle\Normalizer\UniqueNormalizer

  tarnawski.grime_detector.normalizer_factory:
    class: Tarnawski\GrimeDetectorBundle\Normalizer\NormalizerFactory
    arguments:
      - '@tarnawski.grime_detector.lowercase_normalizer'
      - '@tarnawski.grime_detector.stop_words_normalizer'
      - '@tarnawski.grime_detector.unique_normalizer'

  tarnawski.grime_detector.naive_bayes_classifier:
    class: Tarnawski\GrimeDetectorBundle\Classifier\NaiveBayesClassifier
    arguments:
      - '@tarnawski.grime_detector.word.repository'

  tarnawski.grime_detector.processor.comment_processor:
    class: Tarnawski\GrimeDetectorBundle\Processor\CommentProcessor
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@tarnawski.grime_detector.word_tokenizer'
      - '@tarnawski.grime_detector.normalizer_factory'
