services:

  tarnawski.grime_detector.json_store:
    class: Tarnawski\GrimeDetector\DataStore\JsonStore
    arguments:
      - '/var/www/grime-detector/storage.json'

  tarnawski.grime_detector.word_tokenizer:
    class: Tarnawski\GrimeDetector\Tokenizer\WordTokenizer

  tarnawski.grime_detector.lowercase_normalizer:
    class: Tarnawski\GrimeDetector\Normalizer\LowercaseNormalizer

  tarnawski.grime_detector.stop_words_normalizer:
    class: Tarnawski\GrimeDetector\Normalizer\StopWordsNormalizer

  tarnawski.grime_detector.unique_normalizer:
    class: Tarnawski\GrimeDetector\Normalizer\UniqueNormalizer

  tarnawski.grime_detector.data_processor:
    class: Tarnawski\GrimeDetector\Processor\DataProcessor
    arguments:
      - '@tarnawski.grime_detector.json_store'
      - '@tarnawski.grime_detector.word_tokenizer'
      - '@tarnawski.grime_detector.lowercase_normalizer'
      - '@tarnawski.grime_detector.stop_words_normalizer'
      - '@tarnawski.grime_detector.unique_normalizer'

  tarnawski.grime_detector.naive_bayes_classifier:
    class: Tarnawski\GrimeDetector\Classifier\NaiveBayesClassifier
    arguments:
      - '@tarnawski.grime_detector.json_store'
      - '@tarnawski.grime_detector.word_tokenizer'
      - '@tarnawski.grime_detector.lowercase_normalizer'
      - '@tarnawski.grime_detector.stop_words_normalizer'
      - '@tarnawski.grime_detector.unique_normalizer'

