services:
  tarnawski.grime_detector.json_dictionary_store:
    class: Tarnawski\GrimeDetector\DictionaryStore\JsonDictionaryStore
    arguments:
      - '/var/www/grime-detector/dictionary.json'

  tarnawski.grime_detector.word_tokenizer:
    class: Tarnawski\GrimeDetector\Tokenizer\WordTokenizer

  tarnawski.grime_detector.lowercase_normalizer:
    class: Tarnawski\GrimeDetector\Normalizer\LowercaseNormalizer

  tarnawski.grime_detector.stop_words_normalizer:
    class: Tarnawski\GrimeDetector\Normalizer\StopWordsNormalizer

  tarnawski.grime_detector.unique_normalizer:
    class: Tarnawski\GrimeDetector\Normalizer\UniqueNormalizer

  tarnawski.grime_detector.normalizer_factory:
    class: Tarnawski\GrimeDetector\Normalizer\NormalizerFactory
    arguments:
      - '@tarnawski.grime_detector.lowercase_normalizer'
      - '@tarnawski.grime_detector.stop_words_normalizer'
      - '@tarnawski.grime_detector.unique_normalizer'

  tarnawski.grime_detector.data_processor:
    class: Tarnawski\GrimeDetector\Processor\DataProcessor
    arguments:
      - '@tarnawski.grime_detector.word_tokenizer'
      - '@tarnawski.grime_detector.normalizer_factory'

  tarnawski.grime_detector.naive_bayes_classifier:
    class: Tarnawski\GrimeDetector\Classifier\NaiveBayesClassifier


