services:
  grime_detector.word.repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - GrimeDetectorBundle\Entity\Word

  grime_detector.detector.static_strategy:
    class: GrimeDetectorBundle\Detector\Strategy\StaticStrategy
    arguments:
      - '@grime_detector.word.repository'

  grime_detector.detector.strategy_factory:
    class: GrimeDetectorBundle\Detector\StrategyFactory
    arguments:
      - '@grime_detector.detector.static_strategy'

  grime_detector.corrector.grime_corrector:
    class: GrimeDetectorBundle\Corrector\GrimeCorrector
    arguments:
      - '@grime_detector.word.repository'

  grime_detector.service.status_service:
    class: GrimeDetectorBundle\Service\StatusService
    arguments:
      - '@grime_detector.word.repository'
