GrimeDetectorBundle\Entity\CheckedData:
    type: entity
    table: checked_data
    repositoryClass: GrimeDetectorBundle\Repository\CheckedDataRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        text:
            column: value
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        grime:
            column: grime
            type: boolean
            options:
                default: 0
        spam:
            column: spam
            type: boolean
            options:
                default: 0
        date:
            column: date
            type: datetime
            nullable: false

    lifecycleCallbacks: {  }