GrimeDetectorBundle\Entity\Expression:
    type: entity
    table: expression
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        value:
            column: value
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        censuredValue:
            column: censured_value
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        language:
            column: language
            type: string
            nullable: false
            length: 32

    manyToMany:
        types:
            targetEntity: Type
            inversedBy: expression
            joinTable:
                name: expression_type
                joinColumns:
                    expression_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    type_id:
                        referencedColumnName: id

    lifecycleCallbacks: {  }