GrimeDetectorBundle\Entity\Type:
    type: entity
    table: type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            column: name
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
    manyToMany:
        expressions:
            targetEntity: Expression
            mappedBy: types

    lifecycleCallbacks: {  }